[package]
name = "rusty_marble"
version = "0.1.0"
authors = ["keith <keith@the-simmons.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netcdf = "0.2.0"
ndarray = "^0.13.0"
image = "0.22.3"
